### ISSUE TITLE
provisioning: Null value returned by keyLookup function causes unexpected TypeError

### ISSUE THREAD

**Issue by jkehres** [Brightspace/node-auth#62]
This code does not properly handle a `null` value returned by the `opts.keyLookup` callback (which is assigned to `self._latestKey`):
https://github.com/Brightspace/node-auth/blob/2a21ffa023f5ee4c430d963020399ca91bf5fca5/packages/node_modules/brightspace-auth-provisioning/src/index.js#L113

The problem is `typeof null` is `'object'`. Thus, the first condition evaluates to false causing the second condition to be evaluated. The crash occurs when the `kid` field is accessed on the `null` object.

**Comment by omsmith** [comment]
Good catch, will fix.

Wondering about the "causes crash" bit though - it will end up as below, and we'll still be throwing and error - it will just now be the one that we expect. If this is causing a crash-crash, then sounds like there's insufficient error handling on your end?

```js
			if ('object' !== typeof signingKey
				|| null === signingKey
				|| 'string' !== typeof signingKey.kid
				|| 'string' !== typeof signingKey.pem
			) {
				throw new Error('received invalid signing key from "keyLookup"');
			}
```

P.S. If you use the permalink when linking to code (commit hash instead of branch name, hotkey is y) then it will inline the reference in your comment, and, as a permalink is, be more permanent. I edited your post to update.

**Comment by jkehres** [comment]
Crash was a poor choice of words. I just meant that the code was not explicitly throwing an error with a meaningful error message. Instead it was throwing a `TypeError` that caused me to have to dig through the source code of this library to identify the root cause.

**Comment by omsmith** [comment]
Good to hear

**Comment by omsmith** [comment]
https://github.com/Brightspace/node-auth/releases/tag/v6.0.1
